### ISSUE TITLE
LODE Error / Reason: The source can't be downloaded in any permitted format.

### ISSUE THREAD

**Issue by e-e-e** [essepuntato/LODE#11]
I am not sure if this is the correct repository to open this issue, but http://purl.org/co/ is currently redirecting to a page with this error.

> # LODE error
> **Reason:** The source can't be downloaded in any permitted format. # Received fatal alert: handshake_failure # Received fatal alert: handshake_failure # Received fatal alert: handshake_failure # Received fatal alert: handshake_failure # Received fatal alert: handshake_failure # Received fatal alert: handshake_failure

**Comment by essepuntato** [comment]
HI @e-e-e 

Actually, the right repository is https://github.com/collections-ontology/collections-ontology, but since I'm one of the authors of CO, I could deal with it easily.

Now it should work correctly, thanks for pointing to the issue.
Have a nice day :-)

S.

**Comment by e-e-e** [comment]
@essepuntato Thanks so much for the prompt reply and fix.
I really love your work.
