### ISSUE TITLE
Command line version

### ISSUE THREAD

**Issue by AlexanderWillner** [essepuntato/LODE#2]
I would love to see a command line version: lode.sh input.rdf output.html

**Comment by dgarijo** [comment]
@AlexanderWillner I did a wizard that can be invoked as a command here: https://github.com/dgarijo/Widoco.
It uses LODE as well for generating the main documentation of the ontology (see readme file)

**Comment by AlexanderWillner** [comment]
Thanks for the update. Might look at it in the future.
