### ISSUE TITLE
web version offline

### ISSUE THREAD

**Issue by jaygray0919** [essepuntato/LODE#21]
the LODE web services seems to be offline.

**Comment by tfrancart** [comment]
+1 The web version is down and I do have a couple of project that suffer from this unavailability. @essepuntato can you do something about it ?

**Comment by essepuntato** [comment]
We did a major issue with the server that is hosting it, and I don’t know when we will be able to put it up again. I’m trying to figure out if we can to move it on another machine, but I’m not entirely sure it is feasible right now.

**Comment by essepuntato** [comment]
The online version is now usable at another URL, starting with https://w3id.org/lode, e.g. https://w3id.org/lode/owlapi/http://purl.org/spar/cito.

**Comment by fosterlynn** [comment]
Thank you!!  It was very useful for us, and we never found a replacement that gave that same single page output, and that worked.

**Comment by dr-shorthair** [comment]
FWIW my mate @nicholascar has cloned LODE in Python - there is a web-form here https://kurrawong.net/pylode-online

**Comment by tfrancart** [comment]
@fosterlynn Widoco (https://github.com/dgarijo/Widoco) was our offline choice as a replacement for LODE. It integrates LODE in a more comprehensive OWL documentation solution. (any plan to update the ValueFlows documentation generation ?)

**Comment by fosterlynn** [comment]
Thank you very much @dr-shorthair and @tfrancart .

>any plan to update the ValueFlows documentation generation ?

Yes for sure; we will look into the options you have mentioned, and also consider the moved LODE.  The quick solution we implemented (Protege run locally then static output loaded to a server) is very much less than ideal.  For ValueFlows, we still probably need an online solution, but are interested in everything that was mentioned.  Thanks again for your help!

**Comment by fosterlynn** [comment]
>any plan to update the ValueFlows documentation generation ?

Done, thanks again to all.
