### ISSUE TITLE
server down?

### ISSUE THREAD

**Issue by elicolu** [essepuntato/LODE#37]
Hello @essepuntato, 
I noticed that in these last days the server of LODE is down:

Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /lode/extract.
Reason: Error reading from remote server

is it possible to fix it?
I've created my ontology documentation there and I've linked my webGIS app with the ontology semantics.

**Comment by fosterlynn** [comment]
It is down for us also, so probably the same for everyone using it.  Thanks for noticing @elicolu !

P.S. @essepuntato we do appreciate the LODE service, we have used it for several years now!  (You may not hear that often enough. :blush: )

**Comment by essepuntato** [comment]
Dear @fosterlynn and @elicolu,

Thanks for your messages and your interest in LODE. Indeed the server was down, and it has been switched on again yesterday. Now it should work correctly.

Have a nice day :-)
